index-limit = 512
host = "0.0.0.0"
store = "tikv"

[security]
auto-tls = true
ssl-ca = "/config/cert/root.pem"
ssl-cert = "/config/cert/tidb.pem"
ssl-key = "/config/cert/tidb.key"

cluster-ssl-ca = "/config/cert/root.pem"
cluster-ssl-cert = "/config/cert/tidb.pem"
cluster-ssl-key = "/config/cert/tidb.key"